name: Deploy To Production
on:
  pull_request:
    branches:
      - staging
      - development
    types:
      - closed

jobs:
  test-test:
    runs-on: ubuntu-latest
    steps:
      - name: test only
        run: |
          sleep 60
