name: Test Triger Manually
on:
  pull_request:
    branches:
      - staging
      - development
    types: ["closed"]
  workflow_dispatch:
    inputs:
      DeployTo:
        description: 'Deploy To'
        default: 'ALL'
        type: choice
        options:
        - ALL
        - production-relyon
jobs:
  set_target_env:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    name: Define Environment
    runs-on: ubuntu-latest
    outputs:
      env_app: ${{ steps.set_env.outputs.env_value }}
    steps:
      - id: set_env
        run: |
          ## valiadsi input harus dari main untuk workflow dispatch belum
          type="${{ github.ref_type }}" 
          #belum di coba juga nanti kalo tag branch name nya jadi gimana
          getBranchName=${{ github.event_name == 'pull_request' && github.base_ref || inputs.DeployTo == 'ALL' && github.ref_name ||  github.ref_name}}            
          env_value=0

          if [[ "$getBranchName" == 'main' ]]; then
              env_value='production'
          elif [[ "$getBranchName" == 'staging' ]]; then
              env_value='staging'
          elif [[ "$getBranchName" == 'development' ]]; then
              env_value='development'
          fi

          echo "env_value=$env_value" >> "$GITHUB_OUTPUT"

  env-list:
    name: List deploy to ${{ needs.set_target_env.outputs.env_app }}
    needs: set_target_env
    if: needs.set_target_env.outputs.env_app != '0'
    runs-on: ubuntu-latest
    outputs:
      lists: ${{ steps.list_deploy.outputs.ListDeploy }}
    steps:
      - id: list_deploy
        run: |
          envs=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ vars.REPO }}/environments | \
            jq -r '.environments[].name | select(test("${{ needs.set_target_env.outputs.env_app }}"))' | \
            paste -sd, -
            )
          echo "ListDeploy=$envs" >> "$GITHUB_OUTPUT"


  triger-deploy:
    name: Triger to deploy ${{matrix.os}}
    needs:  env-list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04,ubuntu-20.04]
    steps:
      - run: |
          echo "ok"

 
