name: Test Triger Manually
on:
  push:
    branches:
    - development
    - main
  pull_request:
    branches:
      - development
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Deploy To'
        default: 'ALL'
        type: choice
        options:
        - ALL
        - RelyOn Production

jobs:
  set_target_env:
    name: Define Environment
    runs-on: ubuntu-latest
    outputs:
      env_app: ${{ steps.set_env.outputs.env_value }}
    steps:
      - id: set_env
        run: |
          env_value=${{ github.ref_name }}
          echo ${{ github.ref_name }}
          echo "env_value=${env_value}" >> ${GITHUB_OUTPUT}

  log-the-inputs:
    needs:  set_target_env
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.set_target_env.outputs.env_app }}

        #   echo "Log level: $LEVEL"
        #   echo "Tags: $TAGS"
        #   echo "Environment: $ENVIRONMENT"
        #   printenv
        # env:
        #   LEVEL: ${{ inputs.logLevel }}
        #   TAGS: ${{ inputs.tags }}
        #   ENVIRONMENT: ${{ inputs.environment }}
